### ISSUE TITLE
Slides for pitch

### ISSUE THREAD

**Issue by amgoforth** [FAC10/happy#113]
Hi @joeylouise @pbywater @ConchobarMacNessa !

I've made a start on the pitch deck for tomorrow - a few bits on here that you are best placed to do (e.g. tech viability, implementation, and probs product roadmap)...also edit others as you wish.
https://docs.google.com/presentation/d/1Id0q5aHZBFtAniVMdeGsQYBzwfAHPcaXE21yzRp4OV0/edit?usp=sharing
See you tomorrow!

**Comment by joeylouise** [comment]
Thanks @amgoforth, looks great! We'll have a look now
