### ISSUE TITLE
SKYPE DETAILS for 10.30am

### ISSUE THREAD

**Issue by joeylouise** [FAC10/happy#28]
Hey Alex, here are our Skype details, hopefully see you at 10.30!

alice-carr

**Comment by amgoforth** [comment]
I'll be there! Thanks.

**Comment by amgoforth** [comment]
You are in Beijing (according to Skype)?

**Comment by joeylouise** [comment]
Haha, Alice used to live there and hasn't updated her Skype!

**Comment by joeylouise** [comment]
@amgoforth we're having wifi problems, gonna try to call from Skype on the phone!
